### ISSUE TITLE
confine_player_movement() does not work correctly when the width or height of the game window is changed

### ISSUE THREAD

**Issue by chrischtel** [frederickjjoubert/bevy-ball-game#2]
When you change the width of the game window, the "border" moves further out or in. The same applies to the height.

**Comment by Adamkob12** [comment]
check out this article:
https://www.mikechambers.com/blog/2022/10/30/managing-window-size-in-bevy/
You could also send out an WindowResized event to handle it your own way.

**Comment by chrischtel** [comment]
Okay thanks that worked for me.  :)
